# Generated by Django 5.0.2 on 2024-02-08 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('nom_profile', models.CharField(max_length=255)),
                ('nombre_abonner', models.IntegerField(default=0)),
                ('abonnements', models.ManyToManyField(blank=True, related_name='abonnes', to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_modifier', models.DateTimeField(auto_now=True)),
                ('nbre_like', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('video', 'Vidéo')], default='text', max_length=10)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='post_videos/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_comment', models.TextField()),
                ('date_comment', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='app.post')),
                ('video_Associéé', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('utili_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
